spring:
    datasource:
        url: jdbc:mariadb://127.0.0.1:3306/fornecedor
        username: root
        password: a987123a
        testWhileIdle: true
        validationQuery: SELECT 1
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        show-sql: false
        hibernate:
            ddl-auto: create
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
